/**
 * Kawaii / Sanrio-inspired palette — soft pinks, ribbon reds, candy accents.
 * Use these tokens in StyleSheets so the whole app stays cohesive.
 */
export const RoseTheme = {
  colors: {
    primary: '#FF6B9D',
    primaryLight: '#FFB3CE',
    primaryDeep: '#E84A7E',
    secondary: '#FF4D6D',
    accent: '#FFD6E8',
    accentLavender: '#EDE9FE',
    accentButter: '#FEF3C7',
    accentMint: '#D1FAE5',
    soft: '#FFF5F9',
    softLavender: '#FDF4FF',
    border: '#FFC2D8',
    borderLight: '#FFE8F0',
    text: '#6B4E5B',
    textMuted: '#A88F9A',
    background: '#FFFBFC',
    cardWhite: '#FFFFFF',
    gray50: '#FFF0F6',
    iconBackground: '#FFE4F0',
    ribbon: '#FF4D6D',
    fabGlow: '#FF9EC4',
    tabBarBg: '#FFFFFF',
    tabBarBorder: '#FFD6E8',
    teal400: '#7DD3C0',
    teal500: '#5BBFAA',
    macroProtein: '#FF6B9D',
    macroCarbs: '#C4B5FD',
    macroFats: '#FCD34D',
    waterFill: '#FF8FAB',
    waterEmpty: '#E8D4DC',
    waterTrack: '#FFC2D8',
    waterTrackBg: '#FFE4EC',
    streakFire: '#FF758C',
    kittyBow: '#FF1744',
  },
  fonts: {
    regular: 'Quicksand_400Regular',
    medium: 'Quicksand_500Medium',
    semiBold: 'Quicksand_600SemiBold',
    bold: 'Quicksand_700Bold',
  },
};
